#服务端配置
system:
  run-mode: debug # debug、release、test
  host: 0.0.0.0
  http-port: 9000
  is-cors: true #是否启用跨域(启用跨域需要配置cors)
  db-type: mysql #数据库类型 mysql(默认)|sqlite|sqlserver|postgresql|sqlite
  use-multipoint: false  #使用多点登录（false表示使用单点登录）
  router-prefix: "/api" #路由全局前缀
  is-swagger: true #是否路由注册swagger文档访问
  gorm-log-mode: "" #开启Gorm全局日志等级 "silent"、"error"、"warn"、"info" 不填默认info 填入silent可以关闭控制台日志
  gorm-log-zap: false #是否写入zap

# jwt 认证
jwt:
  secret-key: golyadmin-lybbn-insecure-$p1b+kob@eb%wh0bn&8yj&!8
  expires-time: 7d
  buffer-time: 1d

# 验证码配置
captcha:
  captcha-type: string # math 计算、digit 数字、string 英文数字、chinese 中文、audit 音频
  key-length: 5 # 字符个数
  img-width: 240
  img-height: 85

#数据库
databases:
  - db-type: mysql #数据库类型 mysql(默认)|sqlite|sqlserver|postgresql|sqlite
    alias-name: "default" # 数据库的别名，default为默认数据库连接,注意: alias-name 需要在db-list中唯一
    path: "127.0.0.1"
    port: "3306"
    config: "charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local&timeout=1000ms"
    db-name: "lyadmin_go" #数据库名
    username: "root"
    password: "root"
    max-idle-conns: 10 #设置空闲中的最大连接数
    max-open-conns: 100 #设置打开到数据库的最大连接数
  
  # - db-type: sqlite #数据库类型 mysql(默认)|sqlite|sqlserver|postgresql|sqlite
  #   alias-name: "default" # 数据库的别名,注意: alias-name 需要在db-list中唯一
  #   path: "golyadmin.db"
  #   port: ""
  #   config: ""
  #   db-name: ""
  #   username: ""
  #   password: ""
  #   max-idle-conns: 10 #设置空闲中的最大连接数
  #   max-open-conns: 100 #设置打开到数据库的最大连接数

# redis 配置
redis:
  db: 0 # 选择库
  addr: 127.0.0.1:6379
  password: ""

# zap 日志配置
zap:
  level: info #info模式,无错误的堆栈信息,只输出信息、debug:debug模式,有错误的堆栈详细信息、error: error模式,有错误的堆栈详细信息、其他详见zap官方文档
  format: console #格式console、json（线上部署建议这个）
  prefix: "[gitee.com/lybbn/go-vue-lyadmin]" #日志的前缀
  director: logs #存放日志的文件夹
  show-line: true #显示行号
  encode-level: LowercaseColorLevelEncoder #LowercaseLevelEncoder:小写 、LowercaseColorLevelEncoder:小写带颜色、CapitalLevelEncoder: 大写、CapitalColorLevelEncoder: 大写带颜色
  stacktrace-key: stacktrace
  log-in-console: true

# 跨域配置
cors:
  mode: allow-all # 放行模式: allow-all, 放行全部; whitelist, 白名单模式, 来自白名单内域名的请求添加 cors 头; strict-whitelist 严格白名单模式, 白名单外的请求一律拒绝
  whitelist:
    - allow-origin: example1.com
      allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token
      allow-methods: POST, GET, PUT, DELETE, PATCH
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true # 布尔值，请求是否可以包含cookie，HTTP身份验证或客户端SSL证书等用户凭据

    - allow-origin: example2.com
      allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token
      allow-methods: POST, GET, PUT, DELETE, PATCH
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true # 布尔值，请求是否可以包含cookie，HTTP身份验证或客户端SSL证书等用户凭据