info:
  contact: {}
  description: This is a sample Server
  title: Swagger Example API
  version: 0.0.1
paths:
  /api/v1/example/example:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 不分页获取信息
      tags:
      - ExaExample
  /api/v1/example/exampleList:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 分页获取信息列表
      tags:
      - ExaExample
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
